service: url-shortner

plugins:
  - serverless-webpack
custom:
  webpack:
    packager: 'yarn'      # Defaults to npm

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-east-1

  iamRoleStatements:
     - Effect: Allow
       Action:
         - 'dynamodb:PutItem'
         - 'dynamodb:GetItem'
       Resource:
         'Fn::Join':
           - ''
           - - 'arn:aws:dynamodb:'
             - Ref: 'AWS::Region'
             - ':'
             - Ref: 'AWS::AccountId'
             - ':table/'
             - Ref: RedirectionsTable
  environment:
    TOKEN_SIZE: 10
    TABLE_NAME:
      Ref: RedirectionsTable

functions:
  create_redirection:
    handler: redirector.redirector
    events:
      - http:
          path: /submit
          method: post
          cors: true
  redirect:
    handler: redirector.redirect
    events:
      - http:
          path: /{key+}
          method: get
          cors: true

resources:
  Resources:
    RedirectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
